services:
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: .env
    environment:
      TZ: Asia/Seoul
    restart: always
    networks:
      - backend

networks:
  backend:
