server:
  port: 8080

slack:
  url: https://hooks.slack.com/services/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

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dongibuyeo-db.c7gumiik0xja.ap-northeast-2.rds.amazonaws.com:3306/DONG?serverTimezone=Asia/Seoul
    username: jinjoowon
    password: root1234!
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none


shinhan:
  key: 7c746d26c4a44632a638a88131f0b779
  admin:
    email: "admin@dongibuyeo-test.com"
    product: "ADMIN_CH_PRODUCT"
  savings:
    seven:
      bank-code: 088
      subscription-period: 49
      min-balance: 10000
      max-balance: 1000000
      interest-rate: 7.7
  quiz:
    deposit: 10000
    head-count: 10
  challenge:
    member-account: "088-1-e69efd30894448"
    interest-rate: 0.04
    estimate:
      success-rate: 0.82
      bounce-back-rate: 0.2
    money-unit: 10000

  deposit:
    min: 10000
    max: 300000
    unit: 10000
