server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DONG?serverTimezone=Asia/Seoul
    username: jinjoowon
    password: root1234!
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create

shinhan:
  key: 7c746d26c4a44632a638a88131f0b779
  admin:
    email: "admin@dongibuyeo-test.com"
    product: "ADMIN_CHALLENGE_PRODUCT"
