server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DONG?serverTimezone=Asia/Seoul
    username: jinjoowon
    password: root1234!
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

shinhan:
  key: 7c746d26c4a44632a638a88131f0b779
  admin:
    email: "admin@dongibuyeo-test.com"
    product: "ADMIN_CH_PRODUCT"
  savings:
    seven:
      bank-code: 088
      subscription-period: 49
      min-balance: 10000
      max-balance: 1000000
      interest-rate: 7.7
  quiz:
    deposit: 10000
    head-count: 10
  challenge:
    member-account: "088-1-692b220758d742"
  deposit:
    min: 10000
    max: 300000
    unit: 10000